---
- name: copy "{{ service }}" app
  copy: src="{{ service }}" dest=/tmp/ owner=root group=root mode=0755

- name: npm install
  npm: path=/tmp/"{{ service }}"
  when: "{{ service }}" == "counter-panda"

- name: copy "{{ service }}" startup
  become: yes
  copy: src=counter-startup dest=/etc/init/"{{ service }}".conf owner=root group=root mode=0755

- name: restart service
  service:
    - name: "{{ service }}"
    - state: restarted
