---
- name: copy "{{ service }}" app
  synchronize: src="{{ service }}" dest=/tmp/ owner=root group=root mode=0755

- debug:
    msg: " service is {{ service }}"

- name: npm install
  npm: path="/tmp/{{ service }}"
  when: service == "counter-panda"

- name: copy "{{ service }}" startup
  copy: src="{{ service }}-startup" dest="/etc/init/{{ service }}.conf" owner=root group=root mode=0755

- name: restart service
  command: 'stop "{{ service }}" ; start "{{ service }}" '
